from tkinter import *
import smtplib
root=Tk()
menubar=Menu(root)
dash=(5,1,2,1)
filemenu=Menu(menubar)
filemenu.add_command(label="open")
filemenu.add_separator()
filemenu.add_command(label="exit",command=root.destroy)
menubar.add_cascade(label="file",menu=filemenu)
editmenu=Menu(menubar)
editmenu.add_command(label="font")
editmenu.add_command(label="page")
menubar.add_cascade(label="edit",menu=editmenu)
helpmenu=Menu(menubar)
helpmenu.add_command(label="font")
helpmenu.add_command(label="page")
menubar.add_cascade(label="help",menu=helpmenu)
root.config(menu=menubar)
label0=Label(root,text="MAILMAN___ONLINE:A software that redifines the mailing experience giving you the ablity to send mail to multiple user and manuplate inbox")
label0.pack()
topframe=Frame(root)
topframe.pack(side=LEFT)
topframe2=Frame(root)
topframe2.pack(side=LEFT)

label1=Label(topframe,text="LOGIN",fg='red')
label2=Label(topframe,text="PASSWORD",fg='red')
entry1=Entry(topframe2)
entry2=Entry(topframe2)
label1.pack()
label2.pack()
entry1.pack()
entry2.pack()
bottomframe=Frame(root)
bottomframe.pack(side=LEFT)
def button1():
    self=Tk()
    text = Text(self)
    user_input1 = StringVar(self)
    user_input2 = StringVar(self)
    frame2=Frame(self)
    frame2.pack(side=TOP)
    frame3=Frame(self)
    frame3.pack(side=BOTTOM)
    label3 = Label(frame2, text='recipient email id')
    entry = Entry(frame2, textvariable=user_input2)
    label3.pack()
    entry.pack()
    def multiple():
        two=Tk()
        user_input3=StringVar(two)
        user_input4=StringVar(two)
        user_input5=StringVar(two)
        user_input6=StringVar(two)
        entry4=Entry(two,textvariable=user_input3)
        entry5=Entry(two,textvariable=user_input4)
        entry6=Entry(two,textvariable=user_input5)
        entry7=Entry(two,textvariable=user_input6)
        entry4.pack()
        entry5.pack()
        entry6.pack()
        entry7.pack()
        x=[user_input3.get(),user_input4.get(),user_input5.get(),user_input6.get()]
        def sendmessage():
            server = smtplib.SMTP('smtplib.live.com', 587)
            server.starttls()
            server.login('parth15ucs094@outlook.com', 'Parth@1682')
            SenderID = 'parth15ucs094@outlook.com'
            server.sendmail(SenderID, user_input2.get(), user_input1.get())
        def hello():
            for i in (0,1,2,3):
                user_input2=x[i]
                sendmessage()
            two.quit()
        button4=Button(two,text="Submit",bg='yellow',command=hello)
        button4.pack()
    button3=Button(frame2,text='Send to many',bg='blue',fg='white',command=multiple)
    button3.pack()
    label4=Label(frame3,text="Enter your text here.....",bg='white',fg='red')
    label4.pack(side=TOP)
    entry3=Entry(frame3,textvariable=user_input1)
    entry3.pack(side=TOP)
    def sendmessage():
        server = smtplib.SMTP('smtplib@gmail.com', 587)
        server.starttls()
        server.login('parthparashar1647@gmail.com', '')
        SenderID = 'parthparashar1647@gmail.com'
        server.sendmail(SenderID, user_input2.get(), user_input1.get())
    button2=Button(self,text="Send",bg='white',fg='red',command=sendmessage)
    button2.pack(side=BOTTOM)
button1=Button(bottomframe,text="SUBMIT",bg="red",fg="white",command=button1)
button1.pack()
def check1():
    me=Tk()
    list=Listbox(me)
    list.insert(1,'Enter alternate email')
    list.insert(2,'Enter mobile no')
    list.insert(3,'Security Question')
    list.pack()
check=Checkbutton(bottomframe,text="Forget password",bg='yellow',fg='black',command=check1)
check.pack(side=BOTTOM)
root.mainloop()